# Generated by Django 4.1 on 2022-08-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stock_drink_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='type',
            field=models.CharField(max_length=15),
        ),
    ]
